Traceback (most recent call last):
  File "/home/al9001/.conda/envs/ase/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/al9001/.conda/envs/ase/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/al9001/.conda/envs/ase/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/al9001/.conda/envs/ase/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/al9001/.conda/envs/ase/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/al9001/.conda/envs/ase/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/al9001/.conda/envs/ase/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/al9001/.conda/envs/ase/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#:tags: ["hide-output"]
# Boltzmann's constant, J/K
kB = 1.381e-23

# The Lennard-Jones parameters:
A = 1.024e-23   # J.nm^6
B = 1.582e-26   # J.nm^12

# Adjust the units of A and B - they have more manageable values
# in K.nm^6 and K.nm^12
A, B = A / kB, B / kB

# Interatomic distance, in nm
r = np.linspace(0.3, 1, 1000)
# Interatomic potential
U = B/r**12 - A/r**6
# Interatomic force
#F = Put your formula

fig, ax = plt.subplots()
ax.xlim(0.3, 0.8)
ax.ylim(-150, 100)

ax.plot(r, U, 'k', linewidth=2,  label=r'U(r)')

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<module>[0;34m[0m
[1;32m     17[0m [38;5;66;03m# Interatomic force[39;00m
[1;32m     18[0m [38;5;66;03m#F = Put your formula[39;00m
[1;32m     20[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[0;32m---> 21[0m [43max[49m[38;5;241;43m.[39;49m[43mxlim[49m([38;5;241m0.3[39m, [38;5;241m0.8[39m)
[1;32m     22[0m ax[38;5;241m.[39mylim([38;5;241m-[39m[38;5;241m150[39m, [38;5;241m100[39m)
[1;32m     24[0m ax[38;5;241m.[39mplot(r, U, [38;5;124m'[39m[38;5;124mk[39m[38;5;124m'[39m, linewidth[38;5;241m=[39m[38;5;241m2[39m,  label[38;5;241m=[39m[38;5;124mr[39m[38;5;124m'[39m[38;5;124mU(r)[39m[38;5;124m'[39m)

[0;31mAttributeError[0m: 'AxesSubplot' object has no attribute 'xlim'
AttributeError: 'AxesSubplot' object has no attribute 'xlim'

